### ISSUE TITLE
Header parsing

### ISSUE THREAD

**Issue by pschmidtke** [biotite-dev/biotite#195]
Hey, 
is there anything available or planned for pdb or cif header parsing and analysis?

Cheers

Peter

**Comment by padix-key** [comment]
Since the support for PDB files is limited in Biotite, functions for extracting the header or title are not planned for the near future. However, if this functionality is required it would be quite easy to implement.

In contrast, all fields can be read from mmCIF files via the low-level API, including the information from the PDB header:
```python
pdbx_file = pdbx.PDBxFile.read(rcsb.fetch("1l2y", "cif"))
print(pdbx_file["struct_keywords"]["pdbx_keywords"])
print(pdbx_file["pdbx_database_status"]["recvd_initial_deposition_date"])
print(pdbx_file["struct"]["entry_id"])
print(pdbx_file["struct"]["title"])
```
```
DE NOVO PROTEIN
2002-02-25
1L2Y
NMR Structure of Trp-Cage Miniprotein Construct TC5b
```

**Comment by pschmidtke** [comment]
thanks for that detail, that's already a start!

________________________________
