### ISSUE TITLE
How to remove the arrow head while plotting a feature map?

### ISSUE THREAD

**Issue by Sameerpython** [biotite-dev/biotite#274]
Hi,
While plotting the feature map for the operon (as show in your example), i would like to remove the arrow head. How do i do this? 
For the plot_plasmid_map, i did figure out that i could use arrow_head_length=0 for removing the arrow head. 
Is there a possibility to plot the plasmid map as linear rather than circular?

Thanks in advance!!

**Comment by padix-key** [comment]
Hi @Sameerpython, you can customize the way a feature is plotted by writing your own `FeaturePlotter` and giving it as input to the `feature_plotters` of `plot_feature_map()`. This is an example on how this is done: https://www.biotite-python.org/examples/gallery/structure/transketolase_sse.html.

For your purposes you would need to draw a `matplotlib.patches.Rectangle` instead of an `Arrow`.

**Comment by padix-key** [comment]
Did my suggestion solve your issue?

**Comment by padix-key** [comment]
Closed due to inactivity.
