### ISSUE TITLE
CONNECT records not considered during PDB Parsing

### ISSUE THREAD

**Issue by pschmidtke** [biotite-dev/biotite#329]
Quick question,
does biotite consider CONNECT records from PDB files to establish bonds in biotite? I'm mainly asking for non RCSB non standard structures. CONNECT records allow to know which atoms on non standard residues / ligands are connected by a bond. By default bond types are not considered (so only single bonds can reasonably created), but some other formats allow to consider double / tripple bonds (with repeated connect records).

Is that something you plan to integrate into biotite ?

Cheers

Peter

**Comment by padix-key** [comment]
This is indeed a planned feature. Since, it would add overhead to parsing a structure, it will likely be solved using an optional parameter `include_bonds`, similar to `mmtf.get_structure()`. Unfortunately, a PDB file does not provide all bonds, but, as you pointed out, only connections between residues and bonds within standard residues are included, so additional information needs to be leveraged from the *Chemical Component Dictionary*.

**Comment by pschmidtke** [comment]
Hi thanks for considering this.
As this is a planned feature, do you have any timeline so far or not yet?

How are you planning to treat small molecules with CONNECT records but without additional information from the ChemComp dictionary? Are there plans for bond order guessing from PDB files (I know complicated and ugly, just want to understand the scope for now ;) ). Or are there plans to integrate bond order corrections from sources other than the Chemical Component Dictionary?

**Comment by padix-key** [comment]
> As this is a planned feature, do you have any timeline so far or not yet?

There is no fixed timeline for this, but since this feature seems not only relevant to me but also to other users and as it should not be hard to implement, you can expect this feature to be released in the next 1-2 months.

> How are you planning to treat small molecules with CONNECT records but without additional information from the ChemComp dictionary?

In this case the molecule would not get any bonds assigned. If there are `CONECT` records, the PDB format requires that bonds are given for all `HETATM` atoms:

> CONECT records are mandatory for HET groups (excluding water) and for other bonds not specified in the standard residue connectivity table

(https://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT)

In case, the bond information is still missing, you can use `biotite.structure.connect_via_residue_names()`, to guess the bonds and bond orders, if the residues are part of the *Chemical Component Dictionary*.
Otherwise you can use `biotite.structure.connect_via_distances()`: It accurately finds connected atoms in most cases, but is unable to detect the bond order. It is not on my schedule to enhance this method with accurate bond order guessing, since it is complicated as you pointed out, but if someone would contribute code for this, it would be very appreciated.
