### ISSUE TITLE
Misleading information in Biotite Documentation

### ISSUE THREAD

**Issue by jacob-no-cop** [biotite-dev/biotite#363]
Hello,

the documentation of the Biotite submodule "biotite.structrue" (https://www.biotite-python.org/apidoc/biotite.structure.html#module-biotite.structure) says that in order to obtain a deep copy of an AtomArray, the "copy()" method is supposed to be employed. However, this disagrees with the NumPy documentation stating that the mere "copy()" method creates a shallow copy and that  the"deepcopy()" method must be employed if a deep copy is desired ("Note that np.copy is a shallow copy and will not copy object elements within arrays." [...] To ensure all elements within an object array are copied, use copy.deepcopy:[...]").

This is probably not a pitfall for experienced NumPy users, but can be very misleading for less experienced users.

For this reason, it would be great if the documentation could be altered accordingly.

Regards

**Comment by padix-key** [comment]
To my understanding, for most NumPy arrays, deep and shallow copies are equivalent, since they contain only primitive types, e.g. int. The exception are NumPy arrays containing Python objects, that are itself some type of container. For example `numpy.copy()` and `numpy.deepcopy()` would give different results for an NumPy array of Python lists.
However, `AtomArray` does merely contain NumPy arrays containing primitive types. Hence, the internal calls to `numpy.copy()` create deep copies of these arrays.

Does this solve your issue?

**Comment by padix-key** [comment]
I will close the issue for now. If you think the problem still persists, feel free to reopen it.
