### ISSUE TITLE
`get_assembly` does not return both chains for 5zng

### ISSUE THREAD

**Issue by rmrao** [biotite-dev/biotite#387]
### Expected Behavior
5zng is a heterodimer and the biological assembly has two chains. Calling `get_assembly` on the pdbx file should return a structure with both chains, but only the first is returned.

### Example Script
```python
from biotite.structure.io.pdbx import PDBxFile, get_assembly
from biotite.database import rcsb

f = PDBxFile.read(rcsb.fetch("5zng", "cif"))
s = get_assembly(f)
print(set(s.chain_id))
# prints {'A'}
```

It's not clear to me if this is a biotite issue, or if the cif file in PDB is malformed in some way (or if I'm missing something else here).

**Comment by rmrao** [comment]
Looks like something similar happens with 5s6x

**Comment by padix-key** [comment]
Hi, thank you for reporting this. I can reproduce this issue. The reason is that the current implementation expects that each assembly as only one entry in the `pdbx_struct_assembly_gen` category, but in reality multiple entries are possible if different chains require different transformation. I will prepare a PR for this.

**Comment by rmrao** [comment]
Thanks very much for the fast response, this is really awesome!
