### ISSUE TITLE
Difficult to select a specific chain from an assembly

### ISSUE THREAD

**Issue by rmrao** [biotite-dev/biotite#389]
Thanks for the help on the previous issue. Playing around with the assembly loading further, it seems to be very difficult to determine which symmetry a given atom belongs to. I was wondering if it would make sense to add an additional annotation (maybe `state_id` to match pymol's `split_states` command?).

In particular, `pdbx_struct_assembly.oligomeric_count` I believe specifies the number of chains expected in the assembly. It would be nice if, e.g. `len(set(np.char.add(assembly.chain_id, assembly.state_id))) == pdbx_struct_assembly.oligomeric_count` so that it would be easy to select a specific chain from an assembly.

**Comment by padix-key** [comment]
Hi, I am not sure how necessary an additional annotation array (e.g. `state_id`) is, since different chains with the same chain ID can be distinguished with *Biotite*'s chain level utilities for example [get_chain_starts()](https://www.biotite-python.org/apidoc/biotite.structure.get_chain_starts.html).

Using this function such a `state_id` could be also calculated afterwards, if required:
```python
import numpy as np
import biotite.structure as struc
import biotite.structure.io.pdbx as pdbx
from biotite.database import rcsb

pdbx_file = pdbx.PDBxFile.read(rcsb.fetch("3J31", "cif", "."))
assembly = pdbx.get_assembly(pdbx_file)

start_indices = struc.get_chain_starts(assembly, add_exclusive_stop=True)
state_id = np.zeros(assembly.array_length(), dtype=int)
state_id_counter = {chain_id: 0 for chain_id in np.unique(assembly.chain_id)}
for i in range(len(start_indices) - 1):
    start_i = start_indices[i]
    stop_i = start_indices[i+1]
    chain_id = assembly.chain_id[start_i]
    state_id[start_i:stop_i] = state_id_counter[chain_id]
    state_id_counter[chain_id] += 1

assembly.set_annotation("state_id", state_id)

for start_i in start_indices[:-1]:
    print(assembly.chain_id[start_i], assembly.state_id[start_i])
```

Output:
```
Q 0
R 0
A 0
B 0
C 0
D 0
E 0
F 0
G 0
H 0
I 0
J 0
K 0
L 0
M 0
N 0
O 0
P 0
Q 1
R 1
A 1
B 1
C 1
...
```

However, `get_chain_starts()` finds new chains by detecting chain ID changes, so this function would not work properly for assemblies of homodimers. Hence, I think `get_chain_starts()` should also consider the residue ID in the future.

That said, I am not completely supposed to add at least an optional annotation array for this purpose, if cases exist where solutions like the one shown above do not work for a use case.

**Comment by rmrao** [comment]
Thanks again for your work on this. I've been playing around with it and I think the decreased residue ID condition does solve it for homodimers, but unfortunately sometimes PDB numbering causes it to break single chains into multiple chains (e.g. the assembly for 7DFP has chain A residue numbering out of order...)

Currently I'm solving this by sorting residues by chain id, state id, and residue id before invoking biotite chain utilities.

**Comment by padix-key** [comment]
I checked `7DFP` and can confirm the problem. Unfortunately, I see no simple way to detect that it is the same chain here. However, setting `use_author_fields=False` in `get_structure()` or `get_assembly()` solves the problem, since the mmCIF `label_xxx` fields always use consistent numbering, at least to my knowledge.
