### ISSUE TITLE
`structure.io.pdb.get_structure` incorrectly converts all chain IDs to upper case

### ISSUE THREAD

**Issue by naailkhan28** [biotite-dev/biotite#413]
I've been using biotite to get chain IDs for lots of different structures from the PDB, and have noticed an unusual behaviour where all chain IDs are converted to uppercase letters. 

This can sometimes give erroneous behaviour, for example with PDB accession [6HU9](https://www.rcsb.org/structure/6HU9) the file consists of chains A-U and also a-x. In this case `get_chains(structure)` returns a list containing duplicates of A-U. 

It would appear that this behaviour stems from `src/biotite/structure/io/pdb/file.py`:

    for i, line_i in enumerate(annot_i):
                ...
                chain_id[i] = line[_chain_id].upper().strip()
                ...

Removing the `.upper()` seems a simple fix, and has fixed the issue for me locally.

**Comment by padix-key** [comment]
Yes, indeed. At the time of implementation, I thought the PDB format would restrict chain IDs to uppercase letters, probably since this is the most common case. Reading the PDB specification again, I did not found such restriction and the example you provided is a good counterexample. Thank you for spotting this.
