### ISSUE TITLE
`get_chain_starts()` leads to duplicated chains and breaks chain continuity

### ISSUE THREAD

**Issue by edikedik** [biotite-dev/biotite#429]
Hi,

In some cases (for instance, PDB:3i6x), the authors put solvent and ligand atoms after all the protein atoms.

Consider an example with two chains.
```
<Chain A protein residue atoms>
<Chain B protein residue atoms>
<Chain A solvent atoms>
<Chain B solvent atoms>
```

`get_chains_starts()` would treat these as four separate chains as it relies on `chain_id` continuity, which, in such cases, is not kept. This may lead to unexpected results in functions relying on `get_chains_starts()`, such as `chains_iter()` and `apply_chain_wise()`.

Again, renaming the function into something like `get_continuous_chain_starts()` and reimplementing `get_chain_starts()` may be an option.

EDIT: On second thought, in such cases, using `get_chain_starts()` would still lead to ambiguity, whatever the implementation, so the above "option" is not, in fact, an option. Some other solution is needed.

**Comment by padix-key** [comment]
Thanks for your thoughts. However, I am not in favor of such a change for multiple reasons:

- That version of `get_chain_starts()` would be relatively trivial, as it is equivalent to `[np.where(atoms.chain_id == chain_id)[0][0] for chain_id in np.unique(atoms.chain_id)]`. Often even `atoms[atoms.chain_id == desired_chain_id]` would be sufficient for a use case.
- in my experience in most cases chain continuity is desired: In macromolecular assemblies and (if I remember correctly) some structures from PDB different chains have the same `chain_id`. As the function is called `get_chain_starts()` and not `get_chain_id_starts()`, I think this is quite descriptive.
- On the other hand, I would not consider solvent atoms to belong to a previously listed peptide chain. For this reason the mmCIF file for `3i6x` assigns different chain IDs for protein and solvent in the `_atom_site.label_asym_id` field
- This change would be backwards-incompatible (not that important since Biotite is in beta).

**Comment by edikedik** [comment]
Thanks for looking into this. Your comments made me realize this issue arises from the unintuitive `.pdb` format usage, not from `biotite`.
