### ISSUE TITLE
Disregarding gaps in building a sequence logo

### ISSUE THREAD

**Issue by Pinok-io** [biotite-dev/biotite#470]
Hi, biotite is a cool tool that actively helps me in the project. During it, a sequence logo  was needed, and, unfortunately, plot_sequence_logo does not take into account gaps during construction. I fixed this myself by adding gaps to the entropy calculation, but mathematically this may not be the right solution. It would be great to fix this defect.

**Comment by padix-key** [comment]
Hi, thanks for posting this discussion here. I think technically, this would be easily fixable by an optional parameter, that if set also includes gaps in the total count.

However, I wonder how sound this is on the theoretical foundation: The size of each bar is calculated from the entropy

$-\sum_i p_i \ln p_i,$

where $p_i$ is the relative frequency of a symbol at a given profile position. What gives me a headache is, that a gap is not actually a symbol, but a deletion (or insertion in the other sequences). To my understanding standing a gap would mean that a sequence does not contribute to the frequencies at a given position. However, I am not an expert in this topic, so I am curious how other software solve this problem.

If taking gaps into account turns out to be somewhat *'wrong'*, another possibility would be an option to give custom heights as proposed in #361.

**Comment by Pinok-io** [comment]
As I understand it, gaps are usually not taken into account, as they try to align on very similar sequences. In this article(https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-5-7), the method of building a logo is similar, but then it is told about the HMM logo, which I have not figured out yet :(

**Comment by padix-key** [comment]
Thanks for sharing the link, I also skipped over the article. I am neither proficient in profile HMMs, but as I understand Figure 2 of the article, insertions (i.e. gaps to my understanding) are handled using the red empty columns. I think the letter stacks do not take gaps into account. Currently, coloring 'insert state emissions' red would not be possible in Biotite, as HMMs are not implemented.

**Comment by bandrewfox** [comment]
This was a problem for me, too. For example, if a protein alignment has 10 sequences and in one position they are all gaps except for 1 letter, then the sequence Logo and the .to_consensus() function would show that one letter at full height and it would be in the consensus. For example if you paste the following alignment into [WebLogo](https://weblogo.berkeley.edu/logo.cgi), then the position with mostly gaps ends up with a short height (see position 8)

```
MVHATSPKLDRPGRI
MAHASAP-LDRPGRI
MVHAESA-LDRPGRI
MAHATSA-LDRPGRI
MVHVSAP-LDRPGRI
MAHISAP-LDRPGRI
MVHLESA-LDR-GRI
MAHIDSP-LDR-GRI
MAHASAP-LDR-GRI
MVHATAP-LDR-GRI
```

<img width="680" height="188" alt="Image" src="https://github.com/user-attachments/assets/354b2a2c-af43-4a40-a376-1305771f9158" />

I made some fixes in a branch - should I make a PR or do you have some suggestions for my approach?
https://github.com/bandrewfox/biotite-dev/commit/d39f1a595526dcd6eb1649fea469ebe04f137f96
