### ISSUE TITLE
How to write b_factors?

### ISSUE THREAD

**Issue by uros-sipetic** [biotite-dev/biotite#487]
Hello
I'm trying to write b_factors to a PDB file, or rather, trying to store them via the set_structure()
However, I can't seem to understand how to do this.
If I add this attribute to my atom array like this:
`atom_array.b_factor = np.array(b_factors)`
I get proper values when I try and check them
`atom_array.b_factor`
and this works fine. But when I do this
```
pdb_file = fastpdb.PDBFile()
pdb_file.set_structure(atom_array)
```
it is like nothing is stored in the pdb_file object, i.e. I get all zeroes (defaults) when I do this
`pdb_file.get_b_factor()`

Oh and I was using fastpdb, but I was under the impression that it would be the same behaviour? 
Am I missing something crucial here or...?
Thank you for any help!

**Comment by entropybit** [comment]
The b_factors are an extra field, I think if you use ```biotite.structure.io.save_structure``` you will get the desired result.
I have "abused" b-factors for displaying any given quantity on a protein in pymol via ```spectrum b, ...``` many times xD

So you should just do:

```
atom_array.b_factor = np.array(b_factors)
strucio.save_structure("bla.pdb", atom_array)
```
might be that I am forgetting something, if so. A very "stupid" trick is to read in the the PDB file you originall had with

```
strucio.load_structure("origina.pdb", extra_fields=["b_factor"])
```

Otherwise the b_factor property gets ignored.

**Comment by uros-sipetic** [comment]
Ahh thank you @entropybit, the reason that I was going with `set_structure()` is because I am saving multiple models into a list, and then writing them all together to a file, i.e. something like this

```
pdb_files = []
for model in models:  # custom objects
    # Create an atom array structure
    atom_array = create_atom_array(...)  # custom function
    # Create a new PDB file and set its structure to the created AtomArray for the particular model
    pdb_file = fastpdb.PDBFile()
    pdb_file.set_structure(atom_array)
    # Append the pdb_file for the specific model to the pdb_files list
    pdb_files.append(pdb_file)

# Write content to PDB file
write_pdb_files(output_path, models, pdb_files)  # custom function that handles writing multiple model objects to a single PDB file
```
and this all works fine, except that the b_factors do not get written (i.e. I get all zeros as defaults). 
I am setting these in `my create_atom_array()` as I previously described, i.e. `atom_array.b_factor = np.array(b_factors)`
And to verify that the function is correctly setting this, I do get the expected values when I do `atom_array.b_factor`. But not when I do `pdb_file.get_b_factor()`. 
Though if I can handle all of this in a different way, I'd gladly take the suggestions!

**Comment by entropybit** [comment]
Hi @uros-sipetic 

do you really need one pdb with multiple models ? As far as I remember multiple models with PDBFile was an issue some time back. See here:
https://github.com/biotite-dev/biotite/issues/131

**Comment by uros-sipetic** [comment]
Yeah that's why I was writing them like this, in a loop iterating through every model, and then storing the atom arrays into a pdb_files() list, and finally writing everything together to one file.
And this all works fine, except that I can't get the b_factors to get saved

**Comment by entropybit** [comment]
@uros-sipetic 

In fact I was currently extending my comment. So you can have multiple coordinates and write them to a PDB but the annotations, i.e., b_factor, charge etc have to be the same for each model. That is a conceptual foundation of AtomArrayStacks vs AtomArray. For example the following would generate a multiple model PDB with randomly drawn coordinates. Yet, you can only add the b_factor for the AtomArrayStack at the end.

```python
import biotite.structure as struc
import biotite.structure.io as strucio
import numpy as np
prot_arrays = []
for _ in range(10):
    r = np.random.rand(10,3)
    prot = [
        struc.Atom(
            r[i], chain_id="A", res_id=i+1,
            res_name="ALA", atom_name="CA", element="C"
    ) for i in range(r.shape[0])]
    prot_array = struc.array(prot)
    #prot_array.add_annotation("b_factor", dtype=float)
    #prot_array.b_factor = np.random.rand(r.shape[0])
    prot_arrays.append(prot_array)
arr_stack = struc.stack(prot_arrays)
arr_stack.add_annotation("b_factor", dtype=float)
arr_stack.b_factor = np.random.rand(r.shape[0])
strucio.save_structure("random_structs.pdb", arr_stack)
```

**Comment by entropybit** [comment]
> Yeah that's why I was writing them like this, in a loop iterating through every model, and then storing the atom arrays into a `pdb_files` list, and finally writing everything together to one file. And this all works fine, except that I can't get the b_factors to get saved

As I said I am not sure if this currently works in an easy way with b_factors for multiple models. For a single one even with fastpdb it works by setting the b_factor in the annotation before. At least this here works for me:

```python
prot.add_annotation("b_factor", dtype=float)
prot.b_factor = np.random.rand(prot.shape[0])  # random b_factors
out_file = fastpdb.PDBFile()
out_file.set_structure(prot)
out_file.write("fastpdb_random_bfactors.pdb")
```

But I have to admit that it is very annoying to not be able to write features on a per model basis @padix-key 
or am I missing something here ? 
Conceptually this would also not make sense for charges, since the partial charges can in principle vary depending on the 3D positions of the according atoms.

**Comment by uros-sipetic** [comment]
Ahh, this is the line that I was missing:
`atom_array.add_annotation("b_factor", dtype=float)`
and after that we can do 
`atom_array.b_factor = np.array(b_factors)`
while I only did the second line before. 
Thank you @entropybit this solved my problem!

**Comment by padix-key** [comment]
> But I have to admit that it is very annoying to not be able to write features on a per model basis @padix-key
or am I missing something here ?
Conceptually this would also not make sense for charges, since the partial charges can in principle vary depending on the 3D positions of the according atoms.

No, currently it is only possible to have varying coordinates over the models, all other annotations are constant. This is indeed an issue, especially as occupancy may change over the models in the PDB. How to achieve this in a clean way is an entire discussion itself, since both, as per-model and model-independent annotations should be supported. You may open an issue if you like, so we don't forget that this problem exists.
