### ISSUE TITLE
Getting biological assemblies for MMTF files

### ISSUE THREAD

**Issue by ljmartin** [biotite-dev/biotite#488]
Hi Biotite, 
Really getting a lot out of this package, so thank you for providing it. 

I'd like to store a local subset of the PDB for a downstream processing task. MMTF would be a great format because it's fast to load and takes up less storage space relative to mmcif or PDB. However, Biotite can't generate biological assemblies for some MMTF files. 

Is this an inherent limitation of the mmtf format? Or is it something that could be added to biotite in the future? I'm happy to try doing that myself if it's approachable. 
Thanks

**Comment by ljmartin** [comment]
Thanks @padix-key . I think I'll try and have a crack. Presumably it's something that can be done outside of cython, since the PDB version is python-only? Ref: https://github.com/biotite-dev/biotite/blob/feafee3da6526119bcf60a02cfdcd66f626e81f3/src/biotite/structure/io/pdb/file.py#L749

**Comment by padix-key** [comment]
The code for getting an assembly from MMTF resides in [`mmtf.assembly`](https://github.com/biotite-dev/biotite/blob/master/src/biotite/structure/io/mmtf/assembly.py) and would require probably only minor changes. However, currently `get_assembly()` only infers the affected chains from chain ID instead of chain index as normally required by the the [MMTF format](https://github.com/rcsb/mmtf/blob/master/spec.md#bioassemblylist).
Hence `get_structure()` in the Cython module [mmtf.convertfile](https://github.com/biotite-dev/biotite/blob/master/src/biotite/structure/io/mmtf/convertfile.pyx) would also need to be changed to enable it to read the chain index for each atom as additional (optional) annotation.

**Comment by padix-key** [comment]
I will close this, as the MMTF format will be discontinued by the PDB (https://github.com/biotite-dev/biotite/issues/525).

**Comment by ljmartin** [comment]
interesting! thanks for the note
