### ISSUE TITLE
Enable use of specific local CCD version

### ISSUE THREAD

**Issue by ljarosch** [biotite-dev/biotite#591]
Hi! I've been getting into Biotite and saw that there's a lot of handy functionality that relies on the PDB's CCD. As the CCD is getting regularly updated and therefore sometimes not fully compatible with older snapshots of the PDB, I was wondering if it would be possible to get Biotite to use a specific locally stored version of the CCD. Additionally it would be ideal if this could be set up with a conda-installed version of Biotite, whereas the current `setup_ccd.py`, which could probably be adapted to this task, seems to only work with the manual GitHub-based setup.

Would appreciate any advice if there is already a way to do this in the current version!

**Comment by padix-key** [comment]
Hi, as you already pointed out using `setup_ccd.py` is the way to go here (see https://www.biotite-python.org/install.html#updating-the-chemical-component-dictionary). The problem is that Biotite does not ship the original `components.cif`, but a BCIF-compressed subset of it containing only the relevant data. Compiling the original `components.cif` takes a few minutes and even only reading `components.cif` (i.e. indexing the data blocks) takes a few seconds.

Using `setup_ccd.py` with an existing Conda installation can be tricky but should be possible. These are the steps (I have not tested them, but they should work):

- Download the Biotite source code (either via git or the source code release)
- Run `python setup_ccd.py` with the Python environment containing the Conda Biotite installation
- Copy `src/biotite/structure/info/ccd` and replace the directory in the Biotite Conda installation with it.

Alternatively you can read the `components.cif` yourself using [`pdbx.CIFFile`](https://www.biotite-python.org/apidoc/biotite.structure.io.pdbx.CIFFile.html). The metadata for each compound is easy to parse and an `AtomArray` from a data block can be obtained with [`pdbx.get_component`](https://www.biotite-python.org/apidoc/biotite.structure.io.pdbx.get_component.html). However, as noted above, this may take a few seconds.

**Comment by ljarosch** [comment]
Thanks, I'll give this a try!
